;this file for FamiTone2 library generated by text2data tool
; Final version. Structure is identical to original. Only notes changed slightly.

TestMusic3_music_data:
	.byte 2
	.word @instruments
	.word @samples-5
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $03
	.word @env4,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c6,$cf,$cc,$c9,$c7,$c6,$c5,$c4,$c2,$00,$08
@env2:
	.byte $c3,$c7,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env3:
	.byte $c4,$c3,$c2,$c1,$c0,$00,$04
@env4:
	.byte $c2,$06,$c1,$00,$02


@song0ch0:
	.byte $fb,$07
@song0ch0loop:
@ref0:
	; Faster, more melodic lead part
	.byte $80,$3a,$3c,$3a,$39,$3a,$37,$35,$34,$35,$37,$39,$3a,$39,$37,$35
	.byte $83
@ref1:
	.byte $34,$32,$30,$32,$34,$35,$37,$35,$34,$32,$34,$35,$37,$39,$3a,$3c
	.byte $85
@ref2:
	.byte $3a,$3c,$3a,$39,$3a,$37,$35,$34,$35,$37,$39,$3a,$3c,$3d,$3c,$3a
	.byte $83
@ref3:
	.byte $81,$39,$37,$35,$34,$32,$30,$32,$34,$35,$37,$35,$34,$32,$34,$35
	.byte $81
@ref4:
	.byte $37,$35,$34,$32,$34,$35,$37,$39,$3a,$3c,$3a,$39,$3a,$3c,$3d,$3c
@ref5:
	.byte $3a,$39,$37,$35,$34,$32,$30,$bf,$30,$bf,$32,$bf,$34,$bf,$35,$bf
	.byte $81
	.byte $ff,$0e
	.word @ref0
	.byte $ff,$0f
	.word @ref1
	.byte $ff,$0e
	.word @ref2
	.byte $ff,$13
	.word @ref3
	.byte $ff,$10
	.word @ref4
	.byte $ff,$11
	.word @ref5
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref12:
	; Quieter bassline with rests
	.byte $00,$85,$16,$bf,$bf,$bf,$15,$bf,$bf,$bf,$13,$bf,$bf,$bf,$11,$bf
	.byte $81
@ref13:
	.byte $00,$85,$10,$bf,$bf,$bf,$11,$bf,$bf,$bf,$13,$bf,$bf,$bf,$15,$bf
	.byte $81
@ref18:
	.byte $81,$84,$16,$bf,$bf,$bf,$15,$bf,$bf,$bf,$13,$bf,$bf,$bf,$11,$bf
	.byte $81
@ref19:
	.byte $81,$10,$bf,$bf,$bf,$11,$bf,$bf,$bf,$13,$bf,$bf,$bf,$15,$bf,$bf
@ref20:
	.byte $81,$16,$bf,$bf,$bf,$18,$bf,$bf,$bf,$1a,$bf,$bf,$bf,$1b,$bf,$bf
	.byte $81
@ref21:
	.byte $81,$1a,$bf,$bf,$bf,$18,$bf,$bf,$bf,$16,$bf,$bf,$bf,$15,$bf,$bf
	.byte $85
	.byte $ff,$10
	.word @ref12
	.byte $ff,$10
	.word @ref13
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref24:
	; Harmony with rests to be less overpowering
	.byte $80,$26,$bf,$bf,$25,$bf,$bf,$23,$bf,$bf,$21,$bf,$bf,$20,$bf,$bf
	.byte $81
@ref25:
	.byte $1f,$bf,$bf,$20,$bf,$bf,$21,$bf,$bf,$23,$bf,$bf,$25,$bf,$bf,$26
	.byte $81
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref25
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref36:
	; A more standard beat
	.byte $84,$04,$00,$02,$00,$04,$00,$02,$00,$04,$00,$02,$00,$04,$00,$02
	.byte $00,$04,$00,$02,$00,$04,$00,$02,$00,$05,$00,$02,$00,$05,$00,$01
	.byte $81
	.byte $ff,$15
	.word @ref36
	.byte $ff,$15
	.word @ref36
	.byte $ff,$15
	.word @ref36
	.byte $ff,$15
	.word @ref36
	.byte $ff,$15
	.word @ref36
	.byte $ff,$15
	.word @ref36
	.byte $ff,$15
	.word @ref36
	.byte $ff,$15
	.word @ref36
	.byte $ff,$15
	.word @ref36
	.byte $ff,$15
	.word @ref36
	.byte $ff,$15
	.word @ref36
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref48:
	.byte $bf
@ref49:
	.byte $bf
@ref50:
	.byte $bf
@ref51:
	.byte $bf
@ref52:
	.byte $bf
@ref53:
	.byte $bf
@ref54:
	.byte $bf
@ref55:
	.byte $bf
@ref56:
	.byte $bf
@ref57:
	.byte $bf
@ref58:
	.byte $bf
@ref59:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


; --- SONG 1: PAUSE MUSIC (SIMPLE DRONE) ---

@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref60:
	.byte $bf
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref61:
	.byte $bf
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref62:
	; Single low note for drone
	.byte $82,$19,$bf,$bf,$bf,$bf,$bf,$bf,$bf,$bf,$bf,$bf,$bf,$bf
	.byte $85
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref63:
	.byte $bf
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref64:
	.byte $bf
	.byte $fd
	.word @song1ch4loop
